project_name: crossplane-docs

builds:
  - id: crossplane-docs
    binary: crossplane-docs
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - builds:
      - crossplane-docs
    name_template: "{{ .ProjectName }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    wrap_in_directory: false
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md

brews:
  - name: crossplane-docs
    homepage: "https://github.com/Kavinraja-G/crossplane-docs/"
    description: "XDocs generator for Crossplane"
    tap:
      owner: Kavinraja-G
      name: homebrew-tap
