apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xjetpostgresqls.database.wk
spec:
  group: database.wk
  names:
    kind: XJetPostgreSQL
    plural: xjetpostgresqls
  claimNames:
    kind: JetPostgreSQL
    plural: jetpostgresqls
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              description: Required spec field for your API
              properties:
                parameters:
                  type: object
                  properties:
                    storageGB:
                      type: integer
                      description: size of the Database in GB - integer
                      default: 2
                    dbName:
                      type: string
                      description: name of the new DB inside the DB instance - string
                    instanceSize:
                      type: string
                      description: instance size - string
                      default: "large"
                      enum:
                        - small
                        - medium
                        - large
                  required:
                    - storageGB
                    - dbName
                    - instanceSize
              required:
                - parameters
            status:
              type: object
              properties:
                dbConnectionURL:
                  description: String that contains the URL of the Database connection
                  type: string
                status:
                  description: Status of the Database itself
                  type: string
                upgradeEligibility:
                  description: Flag to check eligibility for DB upgrade
                  type: boolean